---
- name: show version
  hosts: "ios-devices"
  gather_facts: false
  connection: local

  vars: 
    cli:
      # Uses resolvable name as hostname in hosts_2 file
      host: "{{ inventory_hostname }}"
      # Note. The username and password are variables instead of statically configured
      username: "{{ ansible_ssh_user }}"
      password: "{{ ansible_ssh_password }}"
#      transport: cli

  tasks:
    - name: show version
      ios_command: 
        commands: show version
        provider: "{{ cli }}"
      
      register: output

    - name: show output
      debug:
        var: output.stdout


