---
- 
  name: Sending IOS Commands
  hosts: dist-r2
  gather_facts: no

  tasks:

  - name: Sending a few simple Cisco IOS commands
    cisco.ios.ios_command:
      commands: 
        - show version
        - show ip int brief
        - show run | section ip route


