---
- name: show version
  hosts: "ios-devices"
  gather_facts: false
  connection: local

  vars: 
    cli:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
#      transport: cli

  tasks:
    - name: show version
      ios_command: 
        commands: show version
        provider: "{{ cli }}"
      
      register: output

    - name: show output
      debug:
        var: output.stdout
   


