---
- name: show version
  hosts: "cisco-devices"
  gather_facts: false
  connection: local

  vars: 
    cli:
      host: "{{ inventory_hostname }}"
      username: cisco
      password: cisco
 #     transport: cli

  tasks:
    - name: show version
      ios_command: 
        commands: show version
        provider: "{{ cli }}"
      
      register: output

    - name: show output
      debug:
        var: output.stdout


